name: ${project.name}
version: ${project.version}
main: ${project.mainClass}
author: ${project.author}
commands:
  bungeeexploitpatch:
    description: Bungee Exploit Patch Command.
    aliases: [bep]